server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: pruebaTecnica
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  datasource:
    url: @dataSource.url@
    username: @dataSource.user@
    password: @dataSource.password@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
    open-in-view: true